export const _costCenter = [
  { code: '7518', label: 'Técnico em Segurança do Trabalho EAD' },
  { code: '7519 ', label: 'Técnico em Automação Industrial EAD' },
  { code: '7521 ', label: 'Técnico em Mecânica' },
  { code: '7556 ', label: 'Qualificação EAD' },
  { code: '7557 ', label: 'Qualificação Presencial' },
  { code: '7563 ', label: 'Aperfeiçoamento Presencial' },
  { code: '7570 ', label: 'Iniciação EAD' },
  { code: '7571 ', label: 'Iniciação Presencial' },
  { code: '7733 ', label: 'Técnico em Eletrotécnica' },
  { code: '7737 ', label: 'Técnico em Edificações' },
  { code: '7750 ', label: 'Superior de Tecnologia em Análise e Desenvolvimento de Sistemas' },
  { code: '7752 ', label: 'Técnico em Vestuário' },
  { code: '7753 ', label: 'Técnico em Automação Industrial' },
  { code: '7754 ', label: 'Técnico em Eletromecânica' },
  { code: '7757 ', label: 'Técnico em Logística' },
  { code: '7758 ', label: 'Técnico em Mecatrônica' },
  { code: '7759 ', label: 'Técnico em Manutenção Automotiva' },
  { code: '7764 ', label: 'Técnico em Modelagem do Vestuário' },
  { code: '7765 ', label: 'Técnico em Têxtil' },
  { code: '7774 ', label: 'Técnico em Química' },
  { code: '7785 ', label: 'Técnico em Produção de Moda' },
  { code: '7786 ', label: 'Superior de Tecnologia em Automação Industrial' },
  { code: '7788 ', label: 'Superior de Tecnologia em Fabricação Mecânica' },
  { code: '7789 ', label: 'Superior de Tecnologia em Redes de Computadores' },
  { code: '7791 ', label: 'Superior de Tecnologia em Mecatrônica Industrial' },
  { code: '7798 ', label: 'Superior de Tecnologia em Desing de Moda' },
  { code: '7804 ', label: 'Pós - Graduação em Negócios do Vestuário EAD' },
  { code: '7932 ', label: 'Aprendizagem - Automotiva' },
  { code: '7933 ', label: 'Aprendizagem - Construção' },
  { code: '7936 ', label: 'Aprendizagem - Eletroeletrônica' },
  { code: '7937 ', label: 'Aprendizagem - Gestão' },
  { code: '7939 ', label: 'Aprendizagem - Metalmecânica' },
  { code: '7940 ', label: 'Aprendizagem - Tecnologia da Informação' },
  { code: '7941 ', label: 'Aprendizagem - Têxtil e Vestuário' },
  { code: '7946 ', label: 'Aprendizagem - Logística' },
  { code: '8071 ', label: 'Aprendizagem - Geral' },
  { code: '8072 ', label: 'Habilitação Técnica - Geral' },
  { code: '8075 ', label: 'Iniciação / Qualificação / Aperfeiçoamento - Geral' },
  { code: '8077 ', label: 'Graduação Tecnológica - Geral' },
  { code: '8078 ', label: 'Pós - Graduação - Geral' },
  { code: '8084 ', label: 'Apoio ao Negócio Educação' },
  { code: '8144 ', label: 'Gestão das Unidades Operacionais' },
  { code: '8452 ', label: 'Responsabilidade Social e Ações Inclusivas' },
  { code: '9184 ', label: 'Técnico em Eletroeletrônica EAD' },
  { code: '10400', label: ' Pós - Graduação em Engenharia de Mecatrônica' },
  { code: '10406', label: ' Engenharia Mecânica' },
  { code: '10605', label: ' Extensão Acadêmica(Presencial)' },
  { code: '10664', label: ' Olimpíada e Concursos de Educação Profissional - Unidades' },
  { code: '10681', label: ' Aprendizagem - Lotação' },
  { code: '10682', label: ' Habilitação / Espec.Técnica / Aprendiz.Técnica - Lotação' },
  { code: '10689', label: ' Iniciação / Qualificação / Aperfeiçoamento - Lotação' },
  { code: '10690', label: ' Aperfeiçoamento - NRs Presencial' },
  { code: '10692', label: ' Graduação Tecnológica - Lotação' },
  { code: '10888', label: ' Aprendizagem - Capacitação' },
  { code: '10889', label: ' Habilitação / Espec.Técnica / Aprendiz.Técnica - Capacitação' },
  { code: '10890', label: ' Iniciação / Qualificação / Aperfeiçoamento - Capacitação' },
  { code: '10891', label: ' Graduação Tecnológica - Capacitação' },
  { code: '10892', label: ' Pós - Graduação - Capacitação' },
  { code: '10893', label: ' Graduação - Bacharelado - Capacitação' },
  { code: '11010', label: ' MDI - Melhoria no Desempenho Industrial' },
  { code: '11876', label: ' Técnico em Desenvolvimento de Sistemas' },
  { code: '11945', label: ' Engenharia de Produção' },
  { code: '11946', label: ' Engenharia de Controle e Automação' },
  { code: '12052', label: ' Técnico em Administração' },
  { code: '12056', label: ' Apoio ao Negócio Educação - Atendimento e Vendas' },
  { code: '12060', label: ' Técnico em Desenvolvimento de Sistemas Integrado ao EM(SESI)' },
  { code: '12135', label: ' Gestão das Unidades Operacionais Comp.' },
  { code: '12144', label: ' Coordenação de Operação Comp.' },
  { code: '12228', label: ' Ações Regionais de Comunicação Interna' },
  { code: '12234', label: ' Apoio ao Negócio Saúde e Segurança SESI / SENAI Comp.' },
  { code: '12399', label: ' Superior de Tecnologia em Automação Industrial EAD' },
  { code: '12405', label: ' Pós - Graduação - Blended Learning - TIC(Presencial)' },
  { code: '12406', label: ' Pós - Graduação - Blended Learning - Gestão(EaD)' },
  { code: '12407', label: ' Extensão - Transformação Social' },
  { code: '12409', label: ' Extensão - Premium(Presencial)' },
  { code: '12412', label: ' Assessoria de Gestão Comercial Comp.' },
  { code: '12414', label: ' Assessoria de Gestão de Pessoas Comp.' },
  { code: '12415', label: ' Assessoria de Gestão Estratégica Comp.' },
  { code: '12445', label: ' Marketing Unidades Regionais - Educação Direto' },
  { code: '12448', label: ' Técnico em Cibersistemas para Automação' },
  { code: '12450', label: ' Extensão Corporativa / Executiva' },
  { code: '12453', label: ' Assessoria de Gestão Operacional Comp.' },
  { code: '12463', label: ' Pós - Graduação - Blended Learning - Moda(EaD)' },
  { code: '12465', label: ' Pós - Graduação - Blended Learning - Metalmecânica(Presencial)' },
  { code: '12470', label: ' Técnico em Mecatrônica Integrado ao EM(SESI)' },
  { code: '12471', label: ' Pós - Graduação - Blended Learning - Gestão(Presencial)' },
  { code: '12531', label: ' Pós - Graduação - Blended Learning - Moda(Presencial)' },
  {
    code: '12551',
    label: ' Coordenadoria Pedagógica e de Qualidade Educacional SESI / SENAI Comp.',
  },
  { code: '12648', label: ' Técnico em Administração EAD' },
  { code: '12656', label: ' Técnico em Desenvolvimento de Sistemas EAD' },
  { code: '12661', label: ' Técnico em Modelagem do Vestuário EAD' },
  { code: '12667', label: ' Técnico em Têxtil EAD' },
  { code: '12736', label: ' Coordenadoria Pedagógica e de Qualidade Educacional' },
];
